### ISSUE TITLE
Empty fringes

### ISSUE THREAD

**Issue by Vanquish081** [webalizer-gt/choppedStraw17#2]
Why does this happen?

<a href="https://imgur.com/EzvEqzw"><img src="https://i.imgur.com/EzvEqzw.png" title="source: imgur.com" /></a>

isn't tipCol

**Comment by webalizer-gt** [comment]
We had a few maps showing this issue. They where all converted from FS15. If this is the case with this map you have to create a new cultivator_density.gdm from a FS17 map.

**Comment by Vanquish081** [comment]
The terrain is imported of GoldCrest Valley with patch v1.5.3.1. 

The map have GMK script too, but the density used for GMK was to normal size, so I resize to 8192 x 8192 same as density for choppedstraw and it seems that it has been solved.

I still don't finish the tests.
